### PR TITLE
Better Web IDL compliance

### PR DESCRIPTION
**Pull request by TimothyGu**
- Disallow calling `AbortController` and `AbortSignal` as functions
- Disallow constructing `AbortSignal` directly

### CODE REVIEW

**Comment by mysticatea** [comment]
LGTM, thank you!

**Comment by TimothyGu** [comment]
@mysticatea Would you mind publishing a new version containing these changes?

**Comment by mysticatea** [comment]
Hi.
I'm sorry for the delay. I had been inactive recently because of my sick.

I will do this weekend.

**Comment by mysticatea** [comment]
I have published v1.0.1. I'm sorry for the delay!

**Comment by TimothyGu** [comment]
@mysticatea Thank you!

**Pull request merged**
